live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x7f8c8d"
blue = "0x3daee9"
cyan = "0x16a085"
green = "0x1cdc9a"
magenta = "0x8e44ad"
red = "0xc0392b"
white = "0xffffff"
yellow = "0xfdbc4b"

[colors.cursor]
cursor = "0xffffff"
text = "0x000000"

[colors.dim]
black = "0x31363b"
blue = "0x1b668f"
cyan = "0x186c60"
green = "0x17a262"
magenta = "0x614a73"
red = "0x783228"
white = "0x63686d"
yellow = "0xb65619"

[colors.normal]
black = "0x232627"
blue = "0x1d99f3"
cyan = "0x1abc9c"
green = "0x11d116"
magenta = "0x9b59b6"
red = "0xed1515"
white = "0xfcfcfc"
yellow = "0xf67400"

[colors.primary]
background = "0x161616"
bright_foreground = "0xffffff"
dim_foreground = "0xfcfcfc"
foreground = "0xffffff"

[colors.selection]
background = "0x1793d1"
text = "0xffffff"

[font]
size = 14

[font.bold]
family = "Emoji Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Emoji Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Emoji Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Emoji Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Control"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.7
title = "Alacritty"

[window.padding]
x = 14
y = 14
